[package]
authors = ["Saverio Miroddi <saverio.pub2@gmail.com>"]
edition = "2018"
name = "cavern-macroquad"
version = "0.1.0"

[dependencies]
macroquad = "0.3"
phf = {version = "0.9.0", features = ["macros"]}
